name: CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install portaudio
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev

    - name: Install Dependencies
      run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r machine-learning-client/requirements.txt
          pip install pytest pytest-cov pylint
      
    - name: Start the Tests
      env:
          PYTHONPATH: machine-learning-client
      run: |
          source venv/bin/activate
          python -m pytest --cov=machine-learning-client/main --cov-report=html
    
    - name: Run linting
      env:
          PYTHONPATH: machine-learning-client
      run: |
          source venv/bin/activate
          pylint machine-learning-client/tests
    
    - name: Run tests with coverage
      env:
          PYTHONPATH: machine-learning-client
      run: |
          source venv/bin/activate
          python -m pytest --cov=machine-learning-client/main --cov-report=html